services:

  db:
    image: postgres:14.1-alpine
    container_name: db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - app-network

  app:
    build: ./src
    container_name: app
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./src/:/usr/src/app/
      - static_volume:/usr/src/app/static  
      - media_volume:/usr/src/app/media   
    depends_on:
      - db
    command: >
      sh -c "python manage.py migrate && python manage.py collectstatic --noinput && 
            gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3"

    restart: always   
    networks:
      - app-network  
    
  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "16379:6379"
    networks:
      - app-network

  celery:
    build: ./src
    container_name: celery
    env_file: 
      - .env
    depends_on:
      - app
      - redis
    command: >
      sh -c "celery -A celery_app worker -l INFO"
    volumes:
      - ./src/:/usr/src/app/
    restart: always
    networks:
      - app-network
  
  flower:
    build: ./src
    container_name: flower
    env_file:
      - .env
    depends_on:
      - app
      - redis
      - celery
    command: >
      sh -c "celery -A celery_app flower --port=5555"
    environment:
      - REDIS_HOST=redis
      - IN_DOCKER=true
    ports:
      - "5555:5555" 
    volumes:
      - ./src/:/usr/src/app/
    restart: always
    networks:
      - app-network


  nginx:
    image: nginx:1.21.6-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    restart: always
    networks:
      - app-network

volumes:
  postgres_data:
  static_volume:
  media_volume:
  redis_data:

networks:
  app-network:
    driver: bridge